### ISSUE TITLE
gRPC for Crystal

### ISSUE THREAD

**Issue by proyb6** [johnjansen/crystal-libraries-needed#99] opened 2018-11-18 16:26 UTC
Still await for gRPC to get attention for Crystal.

https://grpc.io/

FAQ
https://grpc.io/faq/

The pros that gRPC will soon dominate microservices with ease of development and performance benefits open up across your web applications is enormous.

**Comment by RX14** [comment] 2018-11-20 17:11
requires http2, which @ysbaddaden started but isn't production ready.

Making an H2 shard play well with the stdlib (or even including it in the stdlib) likely requires some stdlib work though, see https://github.com/crystal-lang/crystal/issues/6011.

These are all problems which need work before gRPC can be worked on. They'd help other usecases too.

Protobuf seems to be in a working state, see https://github.com/jeromegn/protobuf.cr.

**Comment by proyb6** [comment] 2018-11-21 03:47
Will take a look!

In addition, I haven’t found FlatBuffers in Crystal, would this be feasible to build since the benefits is useful for most case.

**Comment by alexanderadam** [comment] 2018-12-21 11:00
Duplicate of #88

**Closed as completed** 2018-12-21 11:45 UTC
